### ISSUE TITLE
Example requires testthat

### ISSUE THREAD

**Issue by rantahar** [n-kall/priorsense#11] opened 2022-11-16 13:29 UTC
The "powerscale_sensitivity" function used in the README.md example depends on the library "testthat". It's not mentioned or automatically installed as a dependency.

**Comment by n-kall** [comment] 2023-12-13 08:37
This is caused by stan-dev/posterior/issues/329

**Comment by n-kall** [comment] 2023-12-14 12:33
This is now fixed in posterior

**Closed by n-kall** 2023-12-14 12:33 UTC
